### PR TITLE
Removed redundant line in example.

### PR DESCRIPTION
**Pull request by magdairis**
Correct me if I'm wrong, this line has no effect! (callbags noob here!)

### CODE REVIEW

**Comment by franciscotln** [comment]
It has an effect: `interval()` starts the count from 0 then 1, 2... so by mapping x => x + 1 the count is starting from 1, then 2, 3...

**Comment by magdairis** [comment]
@franciscotln yes but isn't this redundant in this case since the following line with `filter(x => x % 2)` filters out any even numbers, including 0? So the `map` line seems to make no practical difference in this particular example.

**Comment by franciscotln** [comment]
The real difference? 1 second in emission :-)
with map it takes 9 seconds, without map it takes 10 seconds, that's the only difference in this example @magdairis

**Comment by magdairis** [comment]
Aha, understood! Shall this be closed then? Or is it better if the readme is simpler? Up to you guys, please close if you prefer!

**Pull request closed without merging**
